# main 向けの pull request がマージされたとき、 backport ラベルがついていたなら prev に向けて cherry-pick pull request を作る
name: cherry-pick to prev
on:
  pull_request:
    types: [closed]

jobs:
  cherry-pick:
    if: github.event.pull_request.merged &&
        contains(github.event.pull_request.labels.*.name, 'backport') &&
        github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/cherry-pick-workflow.yml
    with:
      base: prev
