# マージ済みの p-r に `@astjbot backport` とコメントされたとき、その p-r を prev に cherry-pick する
name: cherry-pick to prev by comment
on:
  issue_comment:
    types : [created]

jobs:
  get-pull-request:
    if: github.event.issue.pull_request &&
        github.event.issue.pull_request.merged_at &&
        contains(github.event.comment.body, '@astjbot backport')
    runs-on: ubuntu-latest
    outputs:
      pr_json: ${{steps.export.outputs.pr_json}}
    steps:
      - name: Get pull request details via JSON
        run: |
          echo 'PR_JSON<<EOF' >> $GITHUB_ENV
          gh api $PR_URL | jq -c . >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.issue.pull_request.url }}
      - id: export
        run: echo "::set-output name=pr_json::$PR_JSON"
      - name: Set reaction
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          ${COMMENT_URL} \
          -f content='+1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_URL: ${{ github.event.comment.reactions.url }}
  cherry-pick:
    needs: [get-pull-request]
    uses: ./.github/workflows/cherry-pick-workflow.yml
    with:
      base: prev
      pull_request_json: ${{ needs.get-pull-request.outputs.pr_json }}
