name: Create a cherry-pick pull request
on:
  workflow_call:
    inputs:
      base:
        description: base branch to cherry-pick to
        type: string
        required: true
      pull_request_json:
        description: json representation of event.pul_request
        type: string
        required: false
        default: ${{ toJSON(github.event.pull_request) }}

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.base }}
    - name: Set Git Identity
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - run: |
        git fetch origin ${MERGE_COMMIT}
        git cherry-pick -m 1 ${MERGE_COMMIT}
      env:
        MERGE_COMMIT: ${{ fromJSON(inputs.pull_request_json).merge_commit_sha }}
    - uses: peter-evans/create-pull-request@v4
      id: create-pull-request
      with:
        title: "backport: ${{ fromJSON(inputs.pull_request_json).title }}"
        body: "Original: ${{ fromJSON(inputs.pull_request_json).html_url }}"
        reviewers: ${{ fromJSON(inputs.pull_request_json).merged_by.login }}
        branch: "backport/${{ fromJSON(inputs.pull_request_json).head.ref }}"
        branch-suffix: short-commit-hash
    # https://qiita.com/osakiy/items/df80db383ce33b82c797
    - name: Post comments (success)
      if: success()
      env:
        PULL_REQUEST_NUMBER: ${{ steps.create-pull-request.outputs.pull-request-number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ fromJSON(inputs.pull_request_json).html_url }}
      run: |
        cat << EOF > comments
        Backported to prev as #${PULL_REQUEST_NUMBER}
        EOF
        gh pr comment -F ./comments "${URL}"
    - name: Post comments (failure)
      if: failure()
      env:
        PULL_REQUEST_NUMBER: ${{ steps.create-pull-request.outputs.pull-request-number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ fromJSON(inputs.pull_request_json).html_url }}
      run: |
        cat << EOF > comments
        Failed to create backport for #${PULL_REQUEST_NUMBER}
        EOF
        gh pr comment -F ./comments "${URL}"
