name: cherry-pick to prev
on:
  pull_request:
    types: [closed]

jobs:
  cherry-pick:
    if: github.event.pull_request.merged &&
        contains(github.event.pull_request.labels.*.name, 'backport') &&
        github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2
    - uses: actions/checkout@v3
      with:
        ref: prev # backport 先のブランチ
    - run: |
        git fetch origin ${MERGE_COMMIT}
        git cherry-pick -m 1 ${MERGE_COMMIT}
      env:
        MERGE_COMMIT: ${{github.event.pull_request.merge_commit_sha}}
    - uses: peter-evans/create-pull-request@v4
      with:
        title: "backport: ${{github.event.pull_request.title}}"
        body: "Original: ${{github.event.pull_request.html_url}}"
        reviewers: ${{github.event.pull_reqest.merged_by.login}}