name: Debug
on:
  pull_request:
    types: [ opened, reopened, closed]
  pull_request_review:
  pull_request_review_comment:
  issue_comment:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2
